version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://estruturas:1234@db:5432/almoxarifado?sslmode=disable
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=almoxarifado-secret-2024
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=estruturas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=almoxarifado
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: